* 9th Commit
** Identifying the source of the bug

 - After implementing the first search requirment.
 - When ~python3 main.py display -n 10 --date 2020-01-01~ it gives the following error:
 [[./1.png]]
 The bug is in line 165 of the 9th commit.

*** What is the error?
The argument of ~strptime~ has been given as None.
- ~str_format~ has been defined in the previous line (line 163), therefore it must be ~date_search.values~

*** Confirming the error
To confirm the suspicions of where the error is, ~date_search.values~ will be printed in line 164. As the image shows, the output is ~[None, None]~, therefore the suspicion is confirmed.
[[./2.png]]
The next steps are backtracing the error to find out where it comes from.

*** Source of the error
First, the query in line 150 will be printed to see whether it is okay there. As seen in the image, the values are still ~[None, None]~. Moreover, it thinks it is of type ~between~, when it should be ~equal~. The error, then, comes from before, when implementing the ~Query~ object.

The problem, therefore, comes from the ~__init__~ function in ~Query~.
That function is built assuming that the parameter-dict ~kwargs~ only has the keys of the values that it contains. Therefore, it assumes that if the date is of type ~equals~, it will not have keys for ~start_date~ and ~end_date~. If it did, the ~if~ statement in line 45 would be true, and the query parameter ~date_search~ would be of type between with ~None~ values.

In order to test this hypothesis, the value of ~flags~ in line 43 will be printed.
[[./4.png]]
The first line in the image shows that, indeed, all the possible flags are part of the ~kwargs~ dictionary. Therefore, the source of the bug has been found.
